### ISSUE TITLE
Add adaptive favicon

### ISSUE THREAD

**Issue by bleudev** [honey-team/honey-team.github.io#16]
Add adaptive favicon which changes when user switches theme between dark and light. For example, in dark theme favicon will be light, in light theme - black. If browser doesn't support this - show orange favicon (like current).

How?

```html
<link rel="icon" href="./icons/favicon.ico" sizes="any"/>
<link rel="icon" href="./icons/favicon.svg" type="image/svg+xml"/>
```

```css
@media (prefers-color-scheme: dark) {
    .favicon { fill: white; }
}

@media (prefers-color-scheme: light) {
    .favicon { fill: black; }
}
```

And add `favicon` class in svg file.
